version: "3"

services:
  nginx:
    image: nginx:1.13.7-alpine
    ports:
      - 80:80
    volumes:
      - ./public:/usr/src
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - graphql
  setup:
    build: ./setup
    volumes:
      - ./setup:/usr/src/app
    depends_on:
      - postgres
  postgres:
    image: postgres:13.3-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=graphql
  graphql:
    build: ./GraphQLServer
    ports:
      - 5050:5050
    volumes:
      - ./GraphQLServer:/usr/src/app
    depends_on:
      - postgres
      - setup
      